version: "3.2"
services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    command: --insecure --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --enable-atom-pub-over-http
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_DEV=true
    networks:
      - backend
  client:
    build:
      context: "."
    command: "npm run start:dev"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - eventstore
    env_file:
      - "./.env"
    environment:
      - EVENT_STORE_HOSTNAME=eventstore
    ports:
      - 3000:3000
    volumes:
      - "./src:/app/src"
    links:
      - eventstore
    networks:
      - backend
networks:
  backend:
    driver: bridge      
